# Generated by Django 5.2.12 on 2026-03-14 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(choices=[('TikTok', 'TikTok'), ('YouTube Shorts', 'YouTube Shorts'), ('Instagram Reels', 'Instagram Reels'), ('Facebook', 'Facebook')], max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_library/')),
                ('file_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image/Thumbnail')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_text', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('SCRIPT', 'Script'), ('RECORDED', 'Recorded'), ('EDITED', 'Edited'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], default='IDEA', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.idea')),
            ],
        ),
    ]
